/**
 * daily-theme-summary-producer.ts — W7 D3
 *
 * Daily cron job (09:00 TST) that:
 *   1. Pulls top themes + company-coverage proxy from the DB.
 *   2. Calls OpenAI gpt-5.4-mini → generates summary_md + theme_label.
 *   3. Upserts into daily_theme_summaries (one row per workspace per day).
 *
 *   NOTE: market_events 24 h pull is intentionally deferred — sourceEventCount
 *   is reported as 0 until market_events ships in the Drizzle schema (W7 D6).
 *
 * Fallback:
 *   If OPENAI_API_KEY is absent or the call fails, writes a rule-template
 *   summary derived from DB theme state (no AI spend, always succeeds).
 *
 * Cost guard:
 *   Prompt is capped at ~800 tokens in, target ~300 tokens out.
 *   At gpt-5.4-mini pricing (~$0.00015/1K input + $0.0006/1K output):
 *   ~800 * 0.00015/1000 + 300 * 0.0006/1000 = $0.00012 + $0.00018 = ~$0.0003/day.
 *   Well under the $0.005/day cap.
 *
 * Hard lines:
 *   - OPENAI_API_KEY env-only, never logged.
 *   - OPENAI_MODEL locked to gpt-5.4-mini (no flip).
 *   - No KGI SDK import.
 *   - DB failure or OpenAI failure → fallback template, never crash.
 */

import { and, desc, gte, eq } from "drizzle-orm";
import {
  companies,
  dailyThemeSummaries,
  getDb,
  themes,
  workspaces
} from "@iuf-trading-room/db";

const OPENAI_MODEL = "gpt-5.4-mini"; // locked, do NOT flip
const OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";
const MAX_PROMPT_THEMES = 6;
const MAX_COMPANY_SAMPLE = 10;

// ── OpenAI raw fetch (no SDK — Node 20 built-in fetch) ────────────────────────

interface OpenAiMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

interface OpenAiResponse {
  choices: { message: { content: string } }[];
}

async function callOpenAi(messages: OpenAiMessage[]): Promise<string | null> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.warn("[daily-theme-summary] OPENAI_API_KEY not set — using fallback template");
    return null;
  }

  try {
    const res = await fetch(OPENAI_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: OPENAI_MODEL,
        messages,
        max_tokens: 400,
        temperature: 0.4
      }),
      signal: AbortSignal.timeout(20_000) // 20s hard timeout
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "(no body)");
      console.error(`[daily-theme-summary] OpenAI ${res.status}: ${body.slice(0, 200)}`);
      return null;
    }

    const data = (await res.json()) as OpenAiResponse;
    return data.choices[0]?.message?.content ?? null;
  } catch (e) {
    console.error("[daily-theme-summary] OpenAI call failed:", e instanceof Error ? e.message : e);
    return null;
  }
}

// ── Parse AI response ─────────────────────────────────────────────────────────

function parseAiResponse(raw: string): { summaryMd: string; themeLabel: string } {
  // Expected format:
  // THEME_LABEL: <≤80 chars>
  // ---
  // <markdown body>
  const lines = raw.trim().split("\n");
  let themeLabel = "";
  let bodyStart = 0;

  for (let i = 0; i < Math.min(lines.length, 3); i++) {
    const line = lines[i]!;
    if (line.startsWith("THEME_LABEL:")) {
      themeLabel = line.replace("THEME_LABEL:", "").trim().slice(0, 80);
      bodyStart = i + 1;
      // skip "---" separator if present
      if (lines[bodyStart]?.trim() === "---") bodyStart++;
      break;
    }
  }

  const summaryMd = lines.slice(bodyStart).join("\n").trim();
  return {
    summaryMd: summaryMd || raw.trim(),
    themeLabel: themeLabel || "Daily Market Overview"
  };
}

// ── Rule-template fallback ────────────────────────────────────────────────────

function buildFallbackSummary(params: {
  date: string;
  topThemes: Array<{ name: string; marketState: string; lifecycle: string; priority: number; thesis: string }>;
  companyCount: number;
  eventCount: number;
}): { summaryMd: string; themeLabel: string } {
  const { date, topThemes, companyCount, eventCount } = params;

  const themeLines = topThemes.map(
    (t) => `- **${t.name}** [${t.lifecycle}/${t.marketState}] priority=${t.priority}: ${t.thesis.slice(0, 120) || "No thesis."}`
  );

  const eventsLine =
    eventCount > 0
      ? `Market events ingested: ${eventCount} | Companies tracked: ${companyCount}`
      : `Companies tracked: ${companyCount} (market_events ingestion deferred to W7 D6)`;

  const summaryMd = [
    `## Daily Theme Summary — ${date}`,
    "",
    eventsLine,
    "",
    "### Active Themes",
    ...themeLines,
    "",
    `_Generated by rule-template fallback (OpenAI unavailable or call failed)._`
  ].join("\n");

  const themeLabel = topThemes[0]?.name
    ? `${topThemes[0].name} [${topThemes[0].marketState}]`
    : "Daily Market Overview";

  return { summaryMd, themeLabel };
}

// ── Main producer ─────────────────────────────────────────────────────────────

export interface DailyThemeSummaryResult {
  summaryId?: string;
  date: string;
  themeLabel: string;
  sourceEventCount: number;
  route: "openai" | "fallback_template" | "skipped_existing";
  skipped: boolean;
  generatedBy: string;
}

export async function runDailyThemeSummaryProducer(): Promise<DailyThemeSummaryResult> {
  const db = getDb();
  if (!db) {
    throw new Error("[daily-theme-summary] PERSISTENCE_MODE must be database");
  }

  const [workspace] = await db.select().from(workspaces).limit(1);
  if (!workspace) throw new Error("[daily-theme-summary] No workspace found");

  const today = new Date().toISOString().split("T")[0]!;

  // Idempotency: skip if already generated today
  const existing = await db
    .select({ id: dailyThemeSummaries.id })
    .from(dailyThemeSummaries)
    .where(
      and(
        eq(dailyThemeSummaries.workspaceId, workspace.id),
        eq(dailyThemeSummaries.dt, today)
      )
    )
    .limit(1);

  if (existing.length > 0) {
    return {
      summaryId: existing[0]!.id,
      date: today,
      themeLabel: "",
      sourceEventCount: 0,
      route: "skipped_existing",
      skipped: true,
      generatedBy: "worker_cron"
    };
  }

  // Gather data
  const topThemes = await db
    .select()
    .from(themes)
    .where(eq(themes.workspaceId, workspace.id))
    .orderBy(desc(themes.priority), desc(themes.updatedAt))
    .limit(MAX_PROMPT_THEMES);

  // Count companies as proxy for "market change signal"
  const companyRows = await db
    .select({ id: companies.id })
    .from(companies)
    .where(eq(companies.workspaceId, workspace.id))
    .limit(MAX_COMPANY_SAMPLE);
  const companyCount = companyRows.length;

  // Source event count: market_events lives in raw SQL (migration 0016) without
  // a Drizzle schema yet. Wiring is deferred to W7 D6 — keep at 0 until then.
  // The fallback summary and the AI prompt both handle 0 gracefully.
  const sourceEventCount = 0;

  // Build themeParams for prompt
  const themeParams = topThemes.map((t) => ({
    name: t.name,
    marketState: t.marketState,
    lifecycle: t.lifecycle,
    priority: t.priority,
    thesis: t.thesis.slice(0, 200)
  }));

  // Attempt OpenAI call
  let summaryMd: string;
  let themeLabel: string;
  let route: "openai" | "fallback_template";
  let generatedBy: string;

  const systemPrompt = [
    "You are a professional equity research assistant for a Taiwan stock trading firm.",
    "Your job is to write a concise daily theme summary for the trading desk.",
    "Output format:",
    "Line 1: THEME_LABEL: <dominant theme label ≤80 chars>",
    "Line 2: ---",
    "Lines 3+: Markdown summary body (200-300 words). Highlight the most active theme, why it matters today, key risks, and watch-list implications.",
    "Do NOT include any preamble or explanation outside this format.",
    "Write in English."
  ].join(" ");

  const userContent = [
    `Date: ${today}`,
    `Top ${themeParams.length} themes by priority:`,
    JSON.stringify(themeParams, null, 2),
    `Company coverage: ${companyCount} companies tracked.`,
    "Generate the daily theme summary."
  ].join("\n");

  const aiResponse = await callOpenAi([
    { role: "system", content: systemPrompt },
    { role: "user", content: userContent }
  ]);

  if (aiResponse) {
    const parsed = parseAiResponse(aiResponse);
    summaryMd = parsed.summaryMd;
    themeLabel = parsed.themeLabel;
    route = "openai";
    generatedBy = `worker_cron:${OPENAI_MODEL}`;
  } else {
    const fallback = buildFallbackSummary({
      date: today,
      topThemes: themeParams,
      companyCount,
      eventCount: sourceEventCount
    });
    summaryMd = fallback.summaryMd;
    themeLabel = fallback.themeLabel;
    route = "fallback_template";
    generatedBy = "worker_cron:fallback_template";
  }

  // Upsert: INSERT ... ON CONFLICT DO UPDATE (idempotent)
  const [inserted] = await db
    .insert(dailyThemeSummaries)
    .values({
      workspaceId: workspace.id,
      dt: today,
      summaryMd,
      themeLabel,
      sourceEventCount,
      generatedBy
    })
    .onConflictDoUpdate({
      target: [dailyThemeSummaries.workspaceId, dailyThemeSummaries.dt],
      set: {
        summaryMd,
        themeLabel,
        sourceEventCount,
        generatedBy
      }
    })
    .returning();

  return {
    summaryId: inserted!.id,
    date: today,
    themeLabel,
    sourceEventCount,
    route,
    skipped: false,
    generatedBy
  };
}
